// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          int64    `protobuf:"varint,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Height               float32  `protobuf:"fixed32,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float64  `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Job                  string   `protobuf:"bytes,10,opt,name=job,proto3" json:"job,omitempty"`
	Company              string   `protobuf:"bytes,11,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Person) GetPhoneNumber() int64 {
	if m != nil {
		return m.PhoneNumber
	}
	return 0
}

func (m *Person) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Person) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Person) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Person) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *Person) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "example.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x85, 0x91, 0x1d, 0xff, 0x4d, 0x42, 0x29, 0x43, 0x29, 0x03, 0xdd, 0xa8, 0x5d, 0x69, 0xd5,
	0x4d, 0x4f, 0xd0, 0x0b, 0x94, 0xa2, 0x0b, 0x04, 0x39, 0x1e, 0x62, 0x95, 0xd8, 0x32, 0x96, 0xfb,
	0x77, 0x85, 0x9e, 0xba, 0x68, 0xec, 0xec, 0xde, 0xf7, 0xe6, 0x2d, 0x3e, 0x06, 0x0e, 0x13, 0xcf,
	0x31, 0x8c, 0xcf, 0xd3, 0x1c, 0x96, 0x80, 0x15, 0xff, 0xb8, 0x61, 0xba, 0xf0, 0xd3, 0x5f, 0x06,
	0xe5, 0xbb, 0x5c, 0x10, 0x61, 0x37, 0xba, 0x81, 0x49, 0x69, 0x65, 0x1a, 0x2b, 0x19, 0x6f, 0x20,
	0xf3, 0x1d, 0x65, 0x5a, 0x99, 0xc2, 0x66, 0xbe, 0xc3, 0x3b, 0x28, 0x78, 0x70, 0xfe, 0x42, 0xb9,
	0x8c, 0x56, 0xc0, 0x5b, 0xc8, 0xdd, 0x99, 0x69, 0x27, 0xb3, 0x14, 0x91, 0xa0, 0x72, 0x5d, 0x37,
	0x73, 0x8c, 0x54, 0xc8, 0xf2, 0x8a, 0xf8, 0x08, 0x87, 0xa9, 0x0f, 0x23, 0x1f, 0xc7, 0xcf, 0xa1,
	0xe5, 0x99, 0x4a, 0xad, 0x4c, 0x6e, 0xf7, 0xd2, 0xbd, 0x49, 0x85, 0x0f, 0xd0, 0xf8, 0x78, 0x74,
	0xa7, 0xc5, 0x7f, 0x31, 0x55, 0x5a, 0x99, 0xda, 0xd6, 0x3e, 0xbe, 0x0a, 0xe3, 0x3d, 0x94, 0x3d,
	0xfb, 0x73, 0xbf, 0x50, 0xad, 0x95, 0xc9, 0xec, 0x46, 0xa9, 0xff, 0x5e, 0xfb, 0x46, 0x2b, 0xa3,
	0xec, 0x46, 0xc9, 0xed, 0x23, 0xb4, 0x04, 0x62, 0x91, 0x62, 0x72, 0x3b, 0x85, 0x61, 0x72, 0xe3,
	0x2f, 0xed, 0x57, 0xb7, 0x0d, 0xdb, 0x52, 0x9e, 0xf3, 0xf2, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x11,
	0x8a, 0xe4, 0xa4, 0x2c, 0x01, 0x00, 0x00,
}
